### ISSUE TITLE
can't clone repo

### ISSUE THREAD

**Issue by naqvisn** [plouc/mozaik-website#10]
can't clone repo for v1 or v2
is that no working anymore?

fatal: Could not read from remote repository.

**Comment by plouc** [comment]
Maybe a git config problem or github? The repo exists as you just created an issue on its project.

**Comment by naqvisn** [comment]
so i tried from multiple machines and asked some friends all can't clone the directory.
I'm trying to setup this on my machine and this is what happens I'm following instructions on the page. 
http://mozaik.rocks/v1/use/

unless there are other instructions and a quick way to use demo and configure as per env.

is there any instructions how i can use my gitlab and jenkins to configure dashboard?

error:
[root@Bilda-Node-0099 ~]# git clone git@github.com:plouc/mozaik-demo.git
Cloning into 'mozaik-demo'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[root@Bilda-Node-0099 ~]#



thanks

**Comment by DeltaEvo** [comment]
@naqvisn You're cloning the repo using ssh, to use this method you need to upload your ssh public key on github

If you don't want to setup it you can use (use http instead of ssh)
 `git clone https://github.com/plouc/mozaik-demo.git`

@plouc I think that the http url should be used on the documentation to avoid this kind of errors

**Comment by naqvisn** [comment]
Yes http worked Thanks

**Comment by plouc** [comment]
@DeltaEvo all the developers/coworkers I know use ssh, so given my (subjective) experience, I'll stick to ssh. Btw the git error is clear enough `Permission denied (publickey).`. IMHO it's far from being advanced git stuff, just basic understanding of it.
