### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by imartyus** [plouc/mozaik-website#14]
Wanted to check out the demo site, however the "DEMO" button leads to a broken heroku app.

**Comment by plouc** [comment]
Well, this probably explains why…

<img width="1104" alt="screenshot 2018-11-29 at 02 31 56" src="https://user-images.githubusercontent.com/501642/49170281-16941600-f37f-11e8-8659-a646bbe5d01a.png">

Will be available next month unless someone's willing to pay for the hosting :)

**Comment by plouc** [comment]
At least it should display this instead of an ugly error.
